### ISSUE TITLE
Issue with  7.2-mam-public-fetch.js

### ISSUE THREAD

**Issue by satishrao** [iota-community/javascript-iota-workshop#18]
Got the below error message while running the 7.2-mam-public-fetch.js

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to parse:  5273152

**Comment by huhn511** [comment]
Thanks for the Issue!

Changes unnecessary with #26 

mam -> changed to IOTA Streams
