### ISSUE TITLE
1-hello-world.js works only with testnet

### ISSUE THREAD

**Issue by johnshearing** [iota-community/javascript-iota-workshop#9]
Running 1-hello-world on the test net works fine but I get the following error when working on the main net.
{ FetchError: request to https://node.tangle.works:443/ failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/home/pi/iota/iota-workshop/node_modules/node-fetch/lib/index.js:1393:11)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:382:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to https://node.tangle.works:443/ failed, reason: read ECONNRESET',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }

The following show the nodes I have tried.
Am I doing something wrong?
Thanks

///////////////////////////////
// Environment Check
///////////////////////////////

const iotaLibrary = require('@iota/core')

const iota = iotaLibrary.composeAPI({
  //provider: 'https://nodes.devnet.thetangle.org:443'
  //provider: 'https://node.tangle.works:443'
  //provider: 'https://n1.iota.nu:443'
  provider: 'https://iota.thathost.net:443'
})

iota
  .getNodeInfo()
  .then(response => console.log(response))
  .catch(err => {
    console.error(err)
  })

**Comment by wesee** [comment]
for my setup, code/1-hello-world.js work for tangle node and the rest of the codes NOT.  all the codes work for iota node (https://nodes.devnet.iota.org:443).  any idea why they do not work on tangle node?

**Comment by johnshearing** [comment]
Hi wesee
I posted the question on the[ IOTA StackExchange](https://iota.stackexchange.com/questions/2328/iota-workshop-functions-on-devnet-only) and the gentleman (Dave) that made the [video](https://www.youtube.com/watch?v=Z-NN0rRcwY0&t=29s) helped by directing me to a [website](https://iota.dance/) that has a list of healthy MainNet Nodes. This solved the problem

**Comment by SammyTS** [comment]
If you want to write a message to mainnet, take a node from the mainnet and change the mwm = 9 to mwm =14 (trytes => iota.sendTrytes (trytes, (depth = 3), (mwm = 9)))
